repos:
  - repo: local
    hooks:
      - id: build-frontend
        name: build-frontend
        language: system
        entry: bash -c 'npm run build && git add src/towelie/static/'
        always_run: true
        pass_filenames: false
        stages: [commit]
      - id: pyright
        name: pyright
        language: system
        entry: uv run pyright
        types: [python]
        pass_filenames: false
